# Generated by Django 5.2 on 2025-04-05 23:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='latestentriesfeeds',
            name='feed_ptr',
        ),
        migrations.DeleteModel(
            name='AddFeed',
        ),
        migrations.DeleteModel(
            name='LatestEntriesFeeds',
        ),
    ]
